server:
  port: 9696

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avarc
    username: avarc
    password: this-is-known-for-standalone-installations

management:
  endpoints:
    web:
      exposure:
        include: "*"
